### ISSUE TITLE
Accept in C the ciphertext including the tag

### ISSUE THREAD

**Issue by ct-clearhaus** [clearhaus/aes256gcm_decrypt#3]
That is, do not input `tag` from Ruby, but split `ciphertext` into `untagged_ciphertext` and `tag` in the C ext.

WDYT?

**Comment by ct-clearhaus** [comment]
If it's not less code (in total) then I vote against myself.

**Comment by mt-clearhaus** [comment]
I like that the magic splitting (the tag length is a bit magic in `data[0..-17]` and `data[-16..-1]`) is contained in the C code, i.e. in the `aes256gcm_decrypt` library. The change is a part of https://github.com/clearhaus/aes256gcm_decrypt/pull/5 .
